definitions:
  configo.ConfigInfo:
    properties:
      configKeys:
        items:
          type: string
        type: array
    type: object
  configo.ConfigObject:
    properties:
      children:
        items:
          $ref: '#/definitions/configo.ConfigObject'
        type: array
      choices:
        items:
          type: string
        type: array
      description:
        type: string
      name:
        type: string
      required:
        type: boolean
      type:
        $ref: '#/definitions/configo.ConfigType'
      value: {}
    type: object
  configo.ConfigType:
    enum:
    - string
    - number
    - boolean
    - json
    - big_text
    - choice
    - parent
    - list
    type: string
    x-enum-varnames:
    - CONFIG_TYPE_STRING
    - CONFIG_TYPE_NUMBER
    - CONFIG_TYPE_BOOLEAN
    - CONFIG_TYPE_JSON
    - CONFIG_TYPE_BIG_TEXT
    - CONFIG_TYPE_CHOICE
    - CONFIG_TYPE_PARENT
    - CONFIG_TYPE_LIST
  configo.ServiceInfo:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  configo.UpdateConfigRequest:
    properties:
      key:
        type: string
      value:
        $ref: '#/definitions/configo.ConfigObject'
    type: object
  configo.configMetadataResponse:
    properties:
      configInfo:
        $ref: '#/definitions/configo.ConfigInfo'
      serviceInfo:
        $ref: '#/definitions/configo.ServiceInfo'
    type: object
info:
  contact:
    email: pavanyewale1996@gmail.com
    name: Developers
    url: http://www.github.com/gofreego
  description: This API is for demonstration purposes only.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://github.com/gofreego/configo/readme.md
  title: Config Manager APIs
  version: "1.0"
paths:
  /configo/config:
    get:
      consumes:
      - application/json
      description: Get config by key
      parameters:
      - description: Config id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/configo.ConfigObject'
        "400":
          description: Bad Request
          schema: {}
      summary: Get config
      tags:
      - Config
    post:
      consumes:
      - application/json
      description: Save config
      parameters:
      - description: config object
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/configo.UpdateConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: config saved successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      summary: Save config
      tags:
      - Config
  /configo/metadata:
    get:
      consumes:
      - application/json
      description: Get all config keys
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/configo.configMetadataResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Get all config keys
      tags:
      - Config
  /configo/web/:
    get:
      consumes:
      - application/json
      description: UI
      produces:
      - text/html
      responses:
        "200":
          description: UI
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      summary: UI
      tags:
      - Config
swagger: "2.0"
